version: '3'
services:
  datadog:
    image: datadog/docker-dd-agent:latest
    environment:
      - DD_HOSTNAME=pyconuk
      - DD_API_KEY=b099f6754c73e62396cf0a02f540e563
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/mounts:/host/proc/mounts:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  api:
    image: makospince/pyconuk-2017:latest
    environment:
      - FLASK_APP=api.py
    command: flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app/
    links:
      - datadog
      - thinker
    ports:
      - "5000:5000"
    networks:
      - default
  thinker:
    image: makospince/pyconuk-2017:latest
    environment:
      - FLASK_APP=api.py
    command: python thinker.py
    volumes:
      - .:/usr/src/app/
    links:
      - datadog
    ports:
      - "5001:8000"
    networks:
      - default
